---

- name: ping
  hosts: test
  tasks: 

    - name: ping test
      ping: 

- name: install packages
  hosts: test
  become: true
  tasks:

    - name: welome message
      command: "wall \"Welcome, let's play a game!\""

    - name: update repos
      apt:
        update_cache: yes

    - name: install python3
      apt:
        name: python3
        state: latest

    - name: install pip
      apt:
        name: python3-pip
        state: latest

    - name: install ufw
      apt:
        name: ufw
        state: latest
    
    - name: install netcat
      apt:
        name: ncat
        state: latest
    
    - name: install git
      apt:
        name: git
        state: latest 

- name: installing fun stuff
  hosts: test
  become: true
  tasks:

    - name: making swsh dir
      command: mkdir /bin/swsh

    - name: cloning starwars shell
      git:
        repo: https://github.com/moloch--/swsh.git
        dest: /bin/swsh
        clone: yes

- name: misconfiguring ufw
  hosts: test
  become: true
  tasks:

    - name: enable ufw
      ufw:
        state: enabled
        rule: allow

    - name: allow ssh
      ufw:
        rule: allow
        port: ssh
        proto: any

    - name: allow high ports tcp
      ufw: 
        rule: allow
        port: 1025:65535
        proto: tcp

    - name: allow high ports udp
      ufw: 
        rule: allow
        port: 1025:65535
        proto: udp

    - name: reload ufw
      ufw:
        state: reloaded
      
